name: greetings
on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3  
      - name: Checkout
        run: git checkout 6290a6f
      - name: Greetings
        run: echo "$(<Greetings.txt)"

