name: greetings
on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Checkout 
        run: |
          git fetch origin 98e446f7b1ee7f799688d495ec51dd96652091fb
          git checkout HEAD^

      - name: Greetings
        run: echo "$(<Greetings.txt)"


